// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvbqxmehtcofoztdyowp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2YnF4bWVodGNvZm96dGR5b3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDYxNzYsImV4cCI6MjA2NjQ4MjE3Nn0.QRHXLXgLUqtZ648mjHMOkV1N-vlPl4tJmO4CisWe7ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);