// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvbqxmehtcofoztdyowp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2YnF4bWVodGNvZm96dGR5b3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDYxNzYsImV4cCI6MjA2NjQ4MjE3Nn0.QRHXLXgLUqtZ648mjHMOkV1N-vlPl4tJmO4CisWe7ec";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

useEffect(() => {
  const fetchAllTieude = async () => {
    const { data, error } = await supabase
      .from('report')
      .select('tieude')
      .order('analysis_date', { ascending: false });
    console.log('DATA TIEUDE:', data, error);
  };
  fetchAllTieude();
}, []);

useEffect(() => {
  const fetchAnalysisResultByTieude = async () => {
    if (!selectedReport) return;
    const idx = playlistItems.findIndex(item => item.id === selectedReport.id);
    const tieude = tieudeList[idx];
    console.log('TIEUDE CHỌN:', tieude);
    const { data, error } = await supabase
      .from('report')
      .select('analysis_result')
      .ilike('tieude', tieude)
      .limit(1)
      .single();
    console.log('DATA ANALYSIS_RESULT:', data, error);
  };
  fetchAnalysisResultByTieude();
}, [selectedReport, tieudeList]);